services:
  db:
    image: postgres:15-alpine
    container_name: sami-website-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: sami-website-app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./logs:/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge